version: "3.8"

services:
  localstack:
    image: localstack/localstack
    container_name: localstack-main
    ports:
      - "4566:4566"
      - "4510:4510"
    environment:
      - DEBUG=0
      - SERVICES=s3,sqs,cloudwatch
    volumes:
      - "./localstack/data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
